ENVIRONMENT:
  MAX_EPISODE_STEPS: 20
SIMULATOR:
  SCENE_DATASET: "mp3d"
  GRID_SIZE: 1.0
  AUDIO:
    RIR_SAMPLING_RATE:  16000
    NORM_TYPE: "l2"
    GT_MONO_MAG_NORM: 1.2
  
    PASSIVE_DATASET_VERSION: "v1"
    SOURCE_AGENT_LOCATION_DATAPOINTS_DIR: "data/passive_datasets/"
    PASSIVE_TRAIN_AUDIO_DIR: "data/audio_data/libriSpeech100Classes_MITMusic_ESC50/1s_chunks/train_preprocessed"
    PASSIVE_NONOVERLAPPING_VAL_AUDIO_DIR: "data/audio_data/libriSpeech100Classes_MITMusic_ESC50/1s_chunks/valUnheard_preprocessed"

    NUM_WORKER: 60 
    BATCH_SIZE: 128 
    NUM_PASSIVE_DATAPOINTS_PER_SCENE: 30000
    NUM_PASSIVE_DATAPOINTS_PER_SCENE_EVAL: 30000 

TASK:
  TYPE: AAViDSS
  SENSORS: ["MIXED_BIN_AUDIO_MAG_SENSOR"]
  GOAL_SENSOR_UUID: mixed_bin_audio_mag
  MEASUREMENTS: []
  POSSIBLE_ACTIONS: []


DATASET:
  TYPE: "AAViDSS"
  SPLIT: "train_731243episodes"
  VERSION: 'v1'
  CONTENT_SCENES: ["*"]
  SCENES_DIR: "data/scene_datasets/mp3d"
  DATA_PATH: "data/active_datasets/{version}/{split}/{split}.json.gz"
